import { Inter } from "next/font/google";
import "./globals.css";
import { Nav } from "@/components/Nav";
import { SpeedInsights } from "@vercel/speed-insights/next";
import AuthProvider from "@/components/AuthProvider";
import { getServerSession } from "next-auth";
import { options } from "@/app/api/auth/[...nextauth]/options";
import Hero from "@/components/Hero";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, modal }) {
  const session = await getServerSession(options);
  const user = session ? session.user : [];

  return (
    <html lang="en">
      <SpeedInsights />
      <AuthProvider>
        <body className={inter.className}>
          <header>
            <Nav />
          </header>
          {session ?          <main className="bg-gray-200 h-max w-full">{children}</main>
  :<Hero/>}
          {modal}
        </body>
      </AuthProvider>
    </html>
  );
}
