import { Inter } from "next/font/google";
import "./globals.css";
import { Nav } from "@/components/Nav";
import { SpeedInsights } from "@vercel/speed-insights/next"


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <SpeedInsights/>
      <body className={inter.className}>
        <header>
          <Nav />
        </header>
        <main className="bg-gray-200 h-max w-full">{children}</main>
      </body>
    </html>
  );
}
